// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/compatibility" | "/admin/consignors" | "/admin/consignors/[id]/sales-report" | "/admin/consignors/payments" | "/admin/crm" | "/admin/crm/clients/[id]" | "/admin/crm/clients/new" | "/admin/finance" | "/admin/finance/accounts" | "/admin/finance/assets" | "/admin/finance/balance-sheet" | "/admin/finance/cash-history" | "/admin/finance/categories" | "/admin/finance/debts" | "/admin/finance/expenses" | "/admin/intelligence" | "/admin/inventory/add" | "/admin/inventory/edit/[productId]" | "/admin/inventory/quick-po-intake" | "/admin/kardex" | "/admin/kardex/[productId]" | "/admin/labels" | "/admin/purchases" | "/admin/repairs" | "/admin/sales" | "/admin/sales/consignor-reports" | "/admin/settings" | "/admin/stock-entry" | "/admin/suppliers" | "/admin/suppliers/[supplierId]" | "/admin/warranties" | "/agent/skills/Desing2026" | "/change-password" | "/checkout" | "/login" | "/pos" | "/products" | "/products/[slug]" | "/reset-password" | "/test-labels" | "/tienda" | "/tienda-admin" | "/tienda-admin/orders" | "/tienda-admin/products" | "/tienda-admin/products/group" | "/tienda-admin/settings" | "/tienda/buscar" | "/tienda/categoria/[slug]" | "/tienda/categorias" | "/tienda/checkout" | "/tienda/cuenta" | "/tienda/cuenta/compras" | "/tienda/cuenta/perfil" | "/tienda/devoluciones" | "/tienda/envios" | "/tienda/favoritos" | "/tienda/garantia" | "/tienda/login" | "/tienda/pagos" | "/tienda/privacidad" | "/tienda/producto/[id]" | "/tienda/terminos"
type AppRouteHandlerRoutes = "/api/check-product" | "/api/clean-duplicate" | "/api/compatibilidad/historial" | "/api/compatibilidad/modelos" | "/api/compatibilidad/registrar" | "/api/consignor-payments" | "/api/consignors" | "/api/consignors/[id]/register-payment" | "/api/consignors/[id]/sales-report" | "/api/correct-inventory" | "/api/create-profiles-table" | "/api/crm/debug-warranty-linking" | "/api/cron/daily-cut" | "/api/debug-auth" | "/api/debug-env" | "/api/debug/check-sale-structure" | "/api/debug/sales-check" | "/api/final-payment" | "/api/force-refresh" | "/api/inventory-validation" | "/api/micas/search" | "/api/public/products" | "/api/purchase-orders" | "/api/quick-po-intake" | "/api/qz/certificate" | "/api/qz/sign" | "/api/repairs/update-details" | "/api/repairs/update-notes" | "/api/repairs/update-status" | "/api/sales" | "/api/sales/[saleId]/change-product" | "/api/sales/cancel" | "/api/settings/labels" | "/api/settings/labels/list" | "/api/setup-deduplication-table" | "/api/setup-profiles" | "/api/test-payment" | "/api/test-supabase"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/tienda-admin" | "/tienda/cuenta"
type RedirectRoutes = never
type RewriteRoutes = "/@vite/client" | "/_next/static/chunks/[[...path]]" | "/favicon.ico"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/_next/static/chunks/[[...path]]": { "path"?: string[]; }
  "/@vite/client": {}
  "/admin": {}
  "/admin/compatibility": {}
  "/admin/consignors": {}
  "/admin/consignors/[id]/sales-report": { "id": string; }
  "/admin/consignors/payments": {}
  "/admin/crm": {}
  "/admin/crm/clients/[id]": { "id": string; }
  "/admin/crm/clients/new": {}
  "/admin/finance": {}
  "/admin/finance/accounts": {}
  "/admin/finance/assets": {}
  "/admin/finance/balance-sheet": {}
  "/admin/finance/cash-history": {}
  "/admin/finance/categories": {}
  "/admin/finance/debts": {}
  "/admin/finance/expenses": {}
  "/admin/intelligence": {}
  "/admin/inventory/add": {}
  "/admin/inventory/edit/[productId]": { "productId": string; }
  "/admin/inventory/quick-po-intake": {}
  "/admin/kardex": {}
  "/admin/kardex/[productId]": { "productId": string; }
  "/admin/labels": {}
  "/admin/purchases": {}
  "/admin/repairs": {}
  "/admin/sales": {}
  "/admin/sales/consignor-reports": {}
  "/admin/settings": {}
  "/admin/stock-entry": {}
  "/admin/suppliers": {}
  "/admin/suppliers/[supplierId]": { "supplierId": string; }
  "/admin/warranties": {}
  "/agent/skills/Desing2026": {}
  "/api/check-product": {}
  "/api/clean-duplicate": {}
  "/api/compatibilidad/historial": {}
  "/api/compatibilidad/modelos": {}
  "/api/compatibilidad/registrar": {}
  "/api/consignor-payments": {}
  "/api/consignors": {}
  "/api/consignors/[id]/register-payment": { "id": string; }
  "/api/consignors/[id]/sales-report": { "id": string; }
  "/api/correct-inventory": {}
  "/api/create-profiles-table": {}
  "/api/crm/debug-warranty-linking": {}
  "/api/cron/daily-cut": {}
  "/api/debug-auth": {}
  "/api/debug-env": {}
  "/api/debug/check-sale-structure": {}
  "/api/debug/sales-check": {}
  "/api/final-payment": {}
  "/api/force-refresh": {}
  "/api/inventory-validation": {}
  "/api/micas/search": {}
  "/api/public/products": {}
  "/api/purchase-orders": {}
  "/api/quick-po-intake": {}
  "/api/qz/certificate": {}
  "/api/qz/sign": {}
  "/api/repairs/update-details": {}
  "/api/repairs/update-notes": {}
  "/api/repairs/update-status": {}
  "/api/sales": {}
  "/api/sales/[saleId]/change-product": { "saleId": string; }
  "/api/sales/cancel": {}
  "/api/settings/labels": {}
  "/api/settings/labels/list": {}
  "/api/setup-deduplication-table": {}
  "/api/setup-profiles": {}
  "/api/test-payment": {}
  "/api/test-supabase": {}
  "/change-password": {}
  "/checkout": {}
  "/favicon.ico": {}
  "/login": {}
  "/pos": {}
  "/products": {}
  "/products/[slug]": { "slug": string; }
  "/reset-password": {}
  "/test-labels": {}
  "/tienda": {}
  "/tienda-admin": {}
  "/tienda-admin/orders": {}
  "/tienda-admin/products": {}
  "/tienda-admin/products/group": {}
  "/tienda-admin/settings": {}
  "/tienda/buscar": {}
  "/tienda/categoria/[slug]": { "slug": string; }
  "/tienda/categorias": {}
  "/tienda/checkout": {}
  "/tienda/cuenta": {}
  "/tienda/cuenta/compras": {}
  "/tienda/cuenta/perfil": {}
  "/tienda/devoluciones": {}
  "/tienda/envios": {}
  "/tienda/favoritos": {}
  "/tienda/garantia": {}
  "/tienda/login": {}
  "/tienda/pagos": {}
  "/tienda/privacidad": {}
  "/tienda/producto/[id]": { "id": string; }
  "/tienda/terminos": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/tienda-admin": never
  "/tienda/cuenta": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
