// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/(admin-tienda)/tienda-admin/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tienda-admin/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin-tienda)/tienda-admin/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin-tienda)/tienda-admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tienda-admin">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin-tienda)/tienda-admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin-tienda)/tienda-admin/products/group/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tienda-admin/products/group">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin-tienda)/tienda-admin/products/group/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin-tienda)/tienda-admin/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tienda-admin/products">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin-tienda)/tienda-admin/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(admin-tienda)/tienda-admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tienda-admin/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin-tienda)/tienda-admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(pos)/pos/mayoreo-config/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pos/mayoreo-config">> = Specific
  const handler = {} as typeof import("../../../src/app/(pos)/pos/mayoreo-config/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(pos)/pos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pos">> = Specific
  const handler = {} as typeof import("../../../src/app/(pos)/pos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(tienda)/tienda/buscar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tienda/buscar">> = Specific
  const handler = {} as typeof import("../../../src/app/(tienda)/tienda/buscar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(tienda)/tienda/categoria/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tienda/categoria/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/(tienda)/tienda/categoria/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(tienda)/tienda/categorias/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tienda/categorias">> = Specific
  const handler = {} as typeof import("../../../src/app/(tienda)/tienda/categorias/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(tienda)/tienda/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tienda/checkout">> = Specific
  const handler = {} as typeof import("../../../src/app/(tienda)/tienda/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(tienda)/tienda/cuenta/compras/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tienda/cuenta/compras">> = Specific
  const handler = {} as typeof import("../../../src/app/(tienda)/tienda/cuenta/compras/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(tienda)/tienda/cuenta/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tienda/cuenta">> = Specific
  const handler = {} as typeof import("../../../src/app/(tienda)/tienda/cuenta/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(tienda)/tienda/cuenta/perfil/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tienda/cuenta/perfil">> = Specific
  const handler = {} as typeof import("../../../src/app/(tienda)/tienda/cuenta/perfil/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(tienda)/tienda/devoluciones/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tienda/devoluciones">> = Specific
  const handler = {} as typeof import("../../../src/app/(tienda)/tienda/devoluciones/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(tienda)/tienda/envios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tienda/envios">> = Specific
  const handler = {} as typeof import("../../../src/app/(tienda)/tienda/envios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(tienda)/tienda/favoritos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tienda/favoritos">> = Specific
  const handler = {} as typeof import("../../../src/app/(tienda)/tienda/favoritos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(tienda)/tienda/garantia/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tienda/garantia">> = Specific
  const handler = {} as typeof import("../../../src/app/(tienda)/tienda/garantia/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(tienda)/tienda/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tienda/login">> = Specific
  const handler = {} as typeof import("../../../src/app/(tienda)/tienda/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(tienda)/tienda/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tienda">> = Specific
  const handler = {} as typeof import("../../../src/app/(tienda)/tienda/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(tienda)/tienda/pagos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tienda/pagos">> = Specific
  const handler = {} as typeof import("../../../src/app/(tienda)/tienda/pagos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(tienda)/tienda/privacidad/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tienda/privacidad">> = Specific
  const handler = {} as typeof import("../../../src/app/(tienda)/tienda/privacidad/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(tienda)/tienda/producto/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tienda/producto/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(tienda)/tienda/producto/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(tienda)/tienda/seminuevos/[modelId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tienda/seminuevos/[modelId]">> = Specific
  const handler = {} as typeof import("../../../src/app/(tienda)/tienda/seminuevos/[modelId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(tienda)/tienda/seminuevos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tienda/seminuevos">> = Specific
  const handler = {} as typeof import("../../../src/app/(tienda)/tienda/seminuevos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(tienda)/tienda/terminos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tienda/terminos">> = Specific
  const handler = {} as typeof import("../../../src/app/(tienda)/tienda/terminos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/auditoria-productos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/auditoria-productos">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/auditoria-productos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/compatibility/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/compatibility">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/compatibility/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/consignors/[id]/sales-report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/consignors/[id]/sales-report">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/consignors/[id]/sales-report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/consignors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/consignors">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/consignors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/consignors/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/consignors/payments">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/consignors/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/crm/clients/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/crm/clients/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/crm/clients/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/crm/clients/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/crm/clients/new">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/crm/clients/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/crm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/crm">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/crm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/delivery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/delivery">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/delivery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/delivery/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/delivery/reports">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/delivery/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/delivery/route/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/delivery/route/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/delivery/route/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/delivery/routes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/delivery/routes">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/delivery/routes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/diagnostico/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/diagnostico">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/diagnostico/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/finance/accounts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/finance/accounts">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/finance/accounts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/finance/assets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/finance/assets">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/finance/assets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/finance/balance-sheet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/finance/balance-sheet">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/finance/balance-sheet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/finance/cash-history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/finance/cash-history">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/finance/cash-history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/finance/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/finance/categories">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/finance/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/finance/debts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/finance/debts">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/finance/debts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/finance/expenses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/finance/expenses">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/finance/expenses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/finance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/finance">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/finance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/intelligence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/intelligence">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/intelligence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/inventario-global/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/inventario-global">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/inventario-global/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/inventory/add/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/inventory/add">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/inventory/add/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/inventory/edit/[productId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/inventory/edit/[productId]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/inventory/edit/[productId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/inventory/quick-po-intake/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/inventory/quick-po-intake">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/inventory/quick-po-intake/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/kardex/[productId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/kardex/[productId]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/kardex/[productId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/kardex/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/kardex">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/kardex/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/labels/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/labels">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/labels/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/purchases/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/purchases">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/purchases/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/repairs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/repairs">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/repairs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/sales/consignor-reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/sales/consignor-reports">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/sales/consignor-reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/sales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/sales">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/sales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/stock-entry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/stock-entry">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/stock-entry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/suppliers/[supplierId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/suppliers/[supplierId]">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/suppliers/[supplierId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/suppliers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/suppliers">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/suppliers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/warranties/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/warranties">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/warranties/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/agent/skills/Desing2026/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agent/skills/Desing2026">> = Specific
  const handler = {} as typeof import("../../../src/app/agent/skills/Desing2026/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/change-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/change-password">> = Specific
  const handler = {} as typeof import("../../../src/app/change-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/mobile/delivery/[routeId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mobile/delivery/[routeId]">> = Specific
  const handler = {} as typeof import("../../../src/app/mobile/delivery/[routeId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../../src/app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/socio/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/socio/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/socio/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/socio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/socio">> = Specific
  const handler = {} as typeof import("../../../src/app/socio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/socio/registro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/socio/registro">> = Specific
  const handler = {} as typeof import("../../../src/app/socio/registro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/socio/seleccionar-sucursal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/socio/seleccionar-sucursal">> = Specific
  const handler = {} as typeof import("../../../src/app/socio/seleccionar-sucursal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/test-labels/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-labels">> = Specific
  const handler = {} as typeof import("../../../src/app/test-labels/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/check-product/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/check-product">> = Specific
  const handler = {} as typeof import("../../../src/app/api/check-product/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/clean-duplicate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/clean-duplicate">> = Specific
  const handler = {} as typeof import("../../../src/app/api/clean-duplicate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/compatibilidad/historial/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/compatibilidad/historial">> = Specific
  const handler = {} as typeof import("../../../src/app/api/compatibilidad/historial/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/compatibilidad/modelos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/compatibilidad/modelos">> = Specific
  const handler = {} as typeof import("../../../src/app/api/compatibilidad/modelos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/compatibilidad/registrar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/compatibilidad/registrar">> = Specific
  const handler = {} as typeof import("../../../src/app/api/compatibilidad/registrar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/consignor-payments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/consignor-payments">> = Specific
  const handler = {} as typeof import("../../../src/app/api/consignor-payments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/consignors/[id]/register-payment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/consignors/[id]/register-payment">> = Specific
  const handler = {} as typeof import("../../../src/app/api/consignors/[id]/register-payment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/consignors/[id]/sales-report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/consignors/[id]/sales-report">> = Specific
  const handler = {} as typeof import("../../../src/app/api/consignors/[id]/sales-report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/consignors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/consignors">> = Specific
  const handler = {} as typeof import("../../../src/app/api/consignors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/correct-inventory/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/correct-inventory">> = Specific
  const handler = {} as typeof import("../../../src/app/api/correct-inventory/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/create-profiles-table/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/create-profiles-table">> = Specific
  const handler = {} as typeof import("../../../src/app/api/create-profiles-table/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/crm/debug-warranty-linking/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/crm/debug-warranty-linking">> = Specific
  const handler = {} as typeof import("../../../src/app/api/crm/debug-warranty-linking/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cron/daily-cut/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/daily-cut">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cron/daily-cut/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/debug-auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug-auth">> = Specific
  const handler = {} as typeof import("../../../src/app/api/debug-auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/debug-env/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug-env">> = Specific
  const handler = {} as typeof import("../../../src/app/api/debug-env/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/debug/check-sale-structure/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/check-sale-structure">> = Specific
  const handler = {} as typeof import("../../../src/app/api/debug/check-sale-structure/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/debug/sales-check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/sales-check">> = Specific
  const handler = {} as typeof import("../../../src/app/api/debug/sales-check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/diagnostics/add-to-inventory/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/diagnostics/add-to-inventory">> = Specific
  const handler = {} as typeof import("../../../src/app/api/diagnostics/add-to-inventory/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/diagnostics/devices/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/diagnostics/devices">> = Specific
  const handler = {} as typeof import("../../../src/app/api/diagnostics/devices/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/diagnostics/download/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/diagnostics/download">> = Specific
  const handler = {} as typeof import("../../../src/app/api/diagnostics/download/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/diagnostics/scan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/diagnostics/scan">> = Specific
  const handler = {} as typeof import("../../../src/app/api/diagnostics/scan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/email/corte/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/email/corte">> = Specific
  const handler = {} as typeof import("../../../src/app/api/email/corte/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/final-payment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/final-payment">> = Specific
  const handler = {} as typeof import("../../../src/app/api/final-payment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/force-refresh/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/force-refresh">> = Specific
  const handler = {} as typeof import("../../../src/app/api/force-refresh/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/inventory-validation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory-validation">> = Specific
  const handler = {} as typeof import("../../../src/app/api/inventory-validation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/micas/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/micas/search">> = Specific
  const handler = {} as typeof import("../../../src/app/api/micas/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/public/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/products">> = Specific
  const handler = {} as typeof import("../../../src/app/api/public/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/purchase-orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/purchase-orders">> = Specific
  const handler = {} as typeof import("../../../src/app/api/purchase-orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/quick-po-intake/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quick-po-intake">> = Specific
  const handler = {} as typeof import("../../../src/app/api/quick-po-intake/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/qz/certificate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/qz/certificate">> = Specific
  const handler = {} as typeof import("../../../src/app/api/qz/certificate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/qz/sign/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/qz/sign">> = Specific
  const handler = {} as typeof import("../../../src/app/api/qz/sign/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/repairs/update-details/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/repairs/update-details">> = Specific
  const handler = {} as typeof import("../../../src/app/api/repairs/update-details/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/repairs/update-notes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/repairs/update-notes">> = Specific
  const handler = {} as typeof import("../../../src/app/api/repairs/update-notes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/repairs/update-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/repairs/update-status">> = Specific
  const handler = {} as typeof import("../../../src/app/api/repairs/update-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/sales/[saleId]/change-product/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sales/[saleId]/change-product">> = Specific
  const handler = {} as typeof import("../../../src/app/api/sales/[saleId]/change-product/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/sales/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sales/cancel">> = Specific
  const handler = {} as typeof import("../../../src/app/api/sales/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/sales/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sales">> = Specific
  const handler = {} as typeof import("../../../src/app/api/sales/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/seminuevo/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/seminuevo/create">> = Specific
  const handler = {} as typeof import("../../../src/app/api/seminuevo/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/settings/labels/list/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/labels/list">> = Specific
  const handler = {} as typeof import("../../../src/app/api/settings/labels/list/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/settings/labels/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/labels">> = Specific
  const handler = {} as typeof import("../../../src/app/api/settings/labels/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/setup-deduplication-table/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/setup-deduplication-table">> = Specific
  const handler = {} as typeof import("../../../src/app/api/setup-deduplication-table/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/setup-profiles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/setup-profiles">> = Specific
  const handler = {} as typeof import("../../../src/app/api/setup-profiles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/test-payment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test-payment">> = Specific
  const handler = {} as typeof import("../../../src/app/api/test-payment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/test-supabase/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/test-supabase">> = Specific
  const handler = {} as typeof import("../../../src/app/api/test-supabase/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/wholesale-profit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/wholesale-profit">> = Specific
  const handler = {} as typeof import("../../../src/app/api/wholesale-profit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/(admin-tienda)/tienda-admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/tienda-admin">> = Specific
  const handler = {} as typeof import("../../../src/app/(admin-tienda)/tienda-admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(pos)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(pos)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(tienda)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(tienda)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(tienda)/tienda/cuenta/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/tienda/cuenta">> = Specific
  const handler = {} as typeof import("../../../src/app/(tienda)/tienda/cuenta/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
